### ISSUE TITLE
Create module that will talk to trakt

### ISSUE THREAD

**Issue by adrianmoisey** [rmotr/003-demo-day-tv-show-countdown#12]
We decided to use `requests` to talk to trakt (https://github.com/rmotr/003-demo-day-tv-show-countdown/issues/10)

It will have two main functions:
- [x] `search(search_term)` - https://github.com/rmotr/003-demo-day-tv-show-countdown/issues/5
- [x] `get_next_episode(show_slug)` #24 #6 

Helper functions:
- [ ] ~~`fetch_show(show_slug)`~~ - https://github.com/rmotr/003-demo-day-tv-show-countdown/issues/21
- [x] `fetch_seasons(show_slug, seasons)`
- [ ] `fetch_episodes(show_slug, season_nbr) `

**Comment by Mester** [comment]
Maybe make the functions work with show id as well?
